
language: c
services:
  - docker

cache:
- directories:
  - "${TRAVIS_BUILD_DIR}/cache"

install:
- true

script:
- cd ${TRAVIS_BUILD_DIR}
- pwd
- mkdir -p public
# Travis Ubuntu doesn't like modern certs for some reason.
# But even modern Ubuntu still throws errors.
- docker run -v `pwd`:`pwd` -w `pwd` -e PYTHONHTTPSVERIFY=0 d2mw/crustaceans python2.7 `pwd`/code/planet.py -v `pwd`/config/config.ini
- ls -lR
- cp -av public/* .
- cp -av static/* .

deploy:
  provider: pages
  skip-cleanup: true
  # local-dir: public
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master

